### ISSUE TITLE
Support for EditorXR 0.1.1

### ISSUE THREAD

**Issue by haywirephoenix** [procore3d/probuilder-vr#38]
Faster and more stable and works with lastest version of unity. Managed to import the 5.6 snapshot build to 2017.3 and fix all the compilation errors but I get an inverted editorvr view and a couple runtime errors.

**Comment by haywirephoenix** [comment]
Is anyone there?

**Comment by karl-** [comment]
Sorry, forgot to update this case.

https://github.com/procore3d/probuilder-vr/releases/tag/v0.1.4b0

**Comment by charlietran** [comment]
@karl- thank you for this, could you include the `unitypackage` file as well in the latest Release?
